$MESS['{VENDOR}_{MODULE}_FILE_MEASURE_B'] = 'Б';
$MESS['{VENDOR}_{MODULE}_FILE_MEASURE_KB'] = 'КБ';
$MESS['{VENDOR}_{MODULE}_FILE_MEASURE_MB'] = 'МБ';
$MESS['{VENDOR}_{MODULE}_FILE_MEASURE_GB'] = 'ГБ';